### ISSUE TITLE
External images should not be encoded

### ISSUE THREAD

**Issue by matteosuppo** [247even/gulp-img64#1]
When you embed an external image

`<img src="http:/i.creativecommons.org/l/by-nc-sa/3.0/it/88x31.png"`>

gulp-img64 returns an error with 

`Error: ENOENT, no such file or directory`

It should instead ignore the external images.

**Comment by cristim** [comment]
@matteosuppo I think you have a typo in the `src`, you have http:**/** (single slash) instead of http:**//** (double slash)
